name: Integração Contínua

on: 
  push:
    branches:
      - develop

jobs:
  executa linter:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"

