name: Integração Contínua

on: 
  push:
    branches:
      - develop

jobs:
  executa linter:
    runs-on: ubuntu-latest
    steps:
      - name: Iniciando processo
        run: echo "Iniciando processo de jobs"

      - name: Checkout
        uses: actions/checkout@v3
       
      - name: Instalando python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11